# theme: minima
# Site Settings
title: Tech blog         # The name of your blog
description: Technology blogs.  # Used for SEO and social sharing
author: Arunkarthik Periyaswamy             # Your name (or pen name)
email: arunkarthikperiyaswamy@gmail.com  # For contact (optional)
baseurl: ""                   # Leave empty for GitHub Pages to work correctly
url: "https://arunkarthik-periyaswamy.github.io/"  # Your GitHub Pages URL (replace 'yourusername')

# Build Settings
theme: minima                 # Simple and clean Jekyll theme (great starting point)
plugins:                      
  - jekyll-feed                # Generates an RSS feed for your blog

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM                   # Enable GitHub Flavored Markdown 
  hard_wrap: false             # Better line wrapping for code blocks

# Collections (for blog posts)
collections:
  posts:
    output: true               # Make sure your posts get published
    permalink: /:categories/:title/ # URL structure for blog posts

# Defaults (for front matter in posts)
defaults:
  - scope:
      path: ""               # Applies to all files
      type: posts             
    values:
      layout: post
      author_profile: true    # Display author information in posts (if available)

# Exclude Files (from the build)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional: Add Google Analytics tracking ID
# google_analytics: UA-XXXXXXXX-X  # Replace with your actual ID
